name: SimpleTags
version: '${project.version}'
main: com.whixard.simpletags.SimpleTags
api-version: 1.19
depend:
    - PlaceholderAPI

commands:
    simpletags:
        description: SimpleTags command
        usage: /simpletags
        aliases: [st]
        permission: simpletags.about
        permission-message: You do not have permission to use this command.
        default: true
    tags:
        description: Tags command
        usage: /tags
        aliases: [tag]
        permission: simpletags.use
        permission-message: You do not have permission to use this command.
        default: true
    streload:
        description: Reloads the plugin
        usage: /streload
        permission: simpletags.reload
        permission-message: You do not have permission to use this command.
        default: true